package interfaces;

import classes.BancoDeDados;
import classes.Idioma;
import classes.Tradutor;
import classes.Usuario;
import classes.UsuarioLogado;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JTextField;


public class CadastroGestores extends javax.swing.JFrame {
    private BancoDeDados bancoDeDados; // Instância do banco de dados
    private Tradutor tradutor; // Tradutor para os textos da interface

    public CadastroGestores(String idiomaAtual) {
        // Obter o usuário logado
        Usuario usuarioLogado = UsuarioLogado.getUsuario();
        // Chamar o método para esconder o menu item se necessário
        esconderMenuItem(usuarioLogado);
        tradutor = new Tradutor(idiomaAtual); // Inicializa o tradutor com o idioma atual
        initComponents(); // Inicializa os componentes da interface
        setTitle(tradutor.traduzir("cadastroUsuario")); // Define o título da janela
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Define a operação padrão ao fechar a janela
        mudarIdioma(idiomaAtual); // Traduz os componentes para o idioma atual

        // Ações dos botões de idioma
        pt_btn.addActionListener(e -> {
            Idioma.setIdiomaAtual("pt");
            mudarIdioma(idiomaAtual); // Atualiza a tradução
        });

        en_btn.addActionListener(e -> {
            Idioma.setIdiomaAtual("en");
            mudarIdioma(idiomaAtual); // Atualiza a tradução
        });

        es_btn.addActionListener(e -> {
            Idioma.setIdiomaAtual("es");
            mudarIdioma(idiomaAtual); // Atualiza a tradução
        });

        pack(); // Ajusta o tamanho da janela
        setVisible(true); // Torna a janela visível
    }
   // public CadastroUsuario() {
    //    initComponents();
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        t_label = new javax.swing.JLabel();
        nm_txt = new javax.swing.JTextField();
        nomeLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        em_txt = new javax.swing.JTextField();
        senhaLabel = new javax.swing.JLabel();
        psw_txt = new javax.swing.JPasswordField();
        psw_btn = new javax.swing.JRadioButton();
        cdt_btn = new javax.swing.JButton();
        pswVisivel_txt = new javax.swing.JTextField();
        end_txt = new javax.swing.JTextField();
        end_label = new javax.swing.JLabel();
        dsc_label = new javax.swing.JLabel();
        dsc2_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        optionsmenu = new javax.swing.JMenu();
        idi_btn = new javax.swing.JMenu();
        pt_btn = new javax.swing.JMenuItem();
        en_btn = new javax.swing.JMenuItem();
        es_btn = new javax.swing.JMenuItem();
        telaini = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(935, 590));
        setResizable(false);
        setSize(new java.awt.Dimension(935, 590));
        getContentPane().setLayout(null);

        t_label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        t_label.setText("Faça Seu Cadastro de Morador");
        getContentPane().add(t_label);
        t_label.setBounds(20, 10, 350, 40);

        nm_txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nm_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nm_txtActionPerformed(evt);
            }
        });
        getContentPane().add(nm_txt);
        nm_txt.setBounds(40, 200, 230, 60);

        nomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeLabel.setText("Nome :");
        getContentPane().add(nomeLabel);
        nomeLabel.setBounds(40, 180, 230, 20);

        emailLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emailLabel.setText("Email:");
        getContentPane().add(emailLabel);
        emailLabel.setBounds(40, 260, 230, 20);

        em_txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        em_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                em_txtActionPerformed(evt);
            }
        });
        getContentPane().add(em_txt);
        em_txt.setBounds(40, 280, 230, 60);

        senhaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        senhaLabel.setText("Senha:");
        getContentPane().add(senhaLabel);
        senhaLabel.setBounds(40, 440, 230, 20);

        psw_txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        psw_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psw_txtActionPerformed(evt);
            }
        });
        getContentPane().add(psw_txt);
        psw_txt.setBounds(40, 460, 230, 60);

        psw_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        psw_btn.setText("mostrar senha");
        psw_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psw_btnActionPerformed(evt);
            }
        });
        getContentPane().add(psw_btn);
        psw_btn.setBounds(310, 460, 160, 21);

        cdt_btn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cdt_btn.setText("cadastrar");
        cdt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdt_btnActionPerformed(evt);
            }
        });
        getContentPane().add(cdt_btn);
        cdt_btn.setBounds(310, 410, 160, 50);
        getContentPane().add(pswVisivel_txt);
        pswVisivel_txt.setBounds(40, 460, 230, 60);

        end_txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(end_txt);
        end_txt.setBounds(40, 370, 230, 60);

        end_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        end_label.setText("Endereço:");
        getContentPane().add(end_label);
        end_label.setBounds(40, 346, 230, 20);

        dsc_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dsc_label.setText("Para realizar o seu cadastro,");
        dsc_label.setToolTipText("");
        dsc_label.setMaximumSize(new java.awt.Dimension(935, 554));
        dsc_label.setMinimumSize(new java.awt.Dimension(935, 554));
        dsc_label.setPreferredSize(new java.awt.Dimension(935, 554));
        getContentPane().add(dsc_label);
        dsc_label.setBounds(20, 60, 390, 30);

        dsc2_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dsc2_label.setText("prencha os campos abaixo");
        getContentPane().add(dsc2_label);
        dsc2_label.setBounds(20, 90, 400, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastro.png"))); // NOI18N
        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 940, 530);

        optionsmenu.setText("opções");

        idi_btn.setText("Idioma");

        pt_btn.setText("Português (pt-br)");
        idi_btn.add(pt_btn);

        en_btn.setText("Inglês (en)");
        idi_btn.add(en_btn);

        es_btn.setText("espanhol (es)");
        idi_btn.add(es_btn);

        optionsmenu.add(idi_btn);

        telaini.setText("Tela Inicial");
        telaini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telainiActionPerformed(evt);
            }
        });
        optionsmenu.add(telaini);

        jMenuBar1.add(optionsmenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1AncestorAdded

    private void em_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_em_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_em_txtActionPerformed

    private void psw_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psw_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psw_txtActionPerformed
    private boolean verificarCampos() {
        // Verifica se os campos obrigatórios estão preenchidos
        if (nm_txt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo Nome deve ser preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
            nm_txt.requestFocus(); // Foca no campo Nome
            return false; // Retorna false se o campo estiver vazio
        }
        if (em_txt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo Email deve ser preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
            em_txt.requestFocus(); // Foca no campo Email
            return false; // Retorna false se o campo estiver vazio
        }
        if (new String(psw_txt.getPassword()).trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo Senha deve ser preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
            psw_txt.requestFocus(); // Foca no campo Senha
            return false; // Retorna false se o campo estiver vazio
        }
        return true; // Retorna true se todos os campos estiverem preenchidos
    }
    private void cdt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdt_btnActionPerformed
        // Ação ao clicar no botão de cadastro
        String nome = nm_txt.getText().trim();
        String email = em_txt.getText().trim();
        String senha = new String(psw_txt.getPassword()).trim();
        String endereco = end_txt.getText().trim();

        if (verificarCampos()) { // Verifica se os campos estão preenchidos
            BancoDeDados banco = new BancoDeDados(); // Cria uma nova instância do banco de dados
            banco.cadastrarGerente(nome, email, senha, endereco); // Cadastra o gerente
            JOptionPane.showMessageDialog(this, tradutor.traduzir("usuarioCadastrado")); // Mensagem de sucesso
            clearFields(); // Limpa os campos após o cadastro
        } else {
            JOptionPane.showMessageDialog(this, tradutor.traduzir("camposVazios"), "Erro", JOptionPane.ERROR_MESSAGE); // Mensagem de erro
        }
    }//GEN-LAST:event_cdt_btnActionPerformed

    private void psw_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psw_btnActionPerformed
        // função para deixar a senha visivel   
        if(psw_btn.isSelected()){
              psw_txt.setVisible(false);
              pswVisivel_txt.setVisible(true);
              pswVisivel_txt.setText(psw_txt.getText());
          } else{
                psw_txt.setVisible(true);
                pswVisivel_txt.setVisible(false);    
          }
    }//GEN-LAST:event_psw_btnActionPerformed

    private void telainiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telainiActionPerformed
        TelaInicial tli = new TelaInicial();
        tli.setVisible(true);
        dispose();
    }//GEN-LAST:event_telainiActionPerformed

    private void nm_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nm_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nm_txtActionPerformed
    private void esconderMenuItem(Usuario usuarioLogado) {
        if (usuarioLogado != null && !usuarioLogado.getTipo().equals("gerente")) {
           telaini.setVisible(false); // Esconde o JMenuItem se não for gerente

        }
    }   
    private void clearFields() {
        // Limpa todos os campos da interface
        nm_txt.setText("");
        em_txt.setText("");
        end_txt.setText("");
        psw_txt.setText("");
    }

    private void traduzirComponentes() {
        // Atualiza os textos da interface de acordo com o idioma atual
        t_label.setText(tradutor.traduzir("tituloCadastroGestor"));
        dsc_label.setText(tradutor.traduzir("descricao1"));
        dsc2_label.setText(tradutor.traduzir("descricao2"));
        optionsmenu.setText(tradutor.traduzir("opcoesMenu"));
        idi_btn.setText(tradutor.traduzir("idiomaMenu"));
        nomeLabel.setText(tradutor.traduzir("nomeLabel"));
        emailLabel.setText(tradutor.traduzir("emailLabel"));
        end_label.setText(tradutor.traduzir("enderecoLabel"));
        senhaLabel.setText(tradutor.traduzir("senhaLabel"));
        psw_btn.setText(tradutor.traduzir("mostrarSenha"));
        cdt_btn.setText(tradutor.traduzir("cadastrar"));
    }
     private void mudarIdioma(String novoIdioma) {
        tradutor = new Tradutor(Idioma.getIdiomaAtual());
        traduzirComponentes(); // Atualiza todos os textos na interface
        setTitle(tradutor.traduzir("cadastroGestores")); // Atualiza o título da janela
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroGestores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroGestores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroGestores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroGestores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new CadastroGestores("pt");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cdt_btn;
    private javax.swing.JLabel dsc2_label;
    private javax.swing.JLabel dsc_label;
    private javax.swing.JTextField em_txt;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JMenuItem en_btn;
    private javax.swing.JLabel end_label;
    private javax.swing.JTextField end_txt;
    private javax.swing.JMenuItem es_btn;
    private javax.swing.JMenu idi_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField nm_txt;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JMenu optionsmenu;
    private javax.swing.JTextField pswVisivel_txt;
    private javax.swing.JRadioButton psw_btn;
    private javax.swing.JPasswordField psw_txt;
    private javax.swing.JMenuItem pt_btn;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JLabel t_label;
    private javax.swing.JMenuItem telaini;
    // End of variables declaration//GEN-END:variables
}
