/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import classes.BancoDeDados;
import classes.Idioma;
import classes.Tradutor;
import classes.UsuarioLogado;
import javax.swing.JOptionPane;

/**
 *
 * @author ryans
 */
public class EnviarSugestoes extends javax.swing.JFrame {
    private Tradutor tradutor;
    private BancoDeDados bancoDeDados;
    /**
     * Creates new form EnviarSugestoes
     */
    public EnviarSugestoes() {
        // Inicializa o tradutor e o banco de dados
        tradutor = new Tradutor(Idioma.getIdiomaAtual());
        bancoDeDados = new BancoDeDados();
        initComponents();
        mudarIdioma(Idioma.getIdiomaAtual());
        
        pt_btn.addActionListener(e -> {
            Idioma.setIdiomaAtual("pt");
                    mudarIdioma(Idioma.getIdiomaAtual());
        });

        en_btn.addActionListener(e -> {
            Idioma.setIdiomaAtual("en");
                    mudarIdioma(Idioma.getIdiomaAtual());
        });
         es_btn.addActionListener(e -> {
            Idioma.setIdiomaAtual("es");
                    mudarIdioma(Idioma.getIdiomaAtual());
        });
        pack(); // Ajusta o tamanho da janela para caber os componentes
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ars_label = new javax.swing.JLabel();
        sgt_label = new javax.swing.JLabel();
        ev_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sgt_txt = new javax.swing.JTextArea();
        label_img = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        optionsmenu = new javax.swing.JMenu();
        idiomamenu = new javax.swing.JMenu();
        pt_btn = new javax.swing.JMenuItem();
        en_btn = new javax.swing.JMenuItem();
        es_btn = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(443, 294));
        setMinimumSize(new java.awt.Dimension(443, 294));
        setPreferredSize(new java.awt.Dimension(443, 294));
        getContentPane().setLayout(null);

        ars_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ars_label.setForeground(new java.awt.Color(255, 255, 255));
        ars_label.setText("Area de sugestões");
        getContentPane().add(ars_label);
        ars_label.setBounds(140, 10, 160, 20);

        sgt_label.setForeground(new java.awt.Color(255, 255, 255));
        sgt_label.setText("Sugestão:");
        getContentPane().add(sgt_label);
        sgt_label.setBounds(140, 50, 130, 16);

        ev_btn.setText("Enviar");
        ev_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ev_btnActionPerformed(evt);
            }
        });
        getContentPane().add(ev_btn);
        ev_btn.setBounds(330, 160, 72, 23);

        sgt_txt.setColumns(1);
        sgt_txt.setLineWrap(true);
        sgt_txt.setRows(5);
        sgt_txt.setTabSize(5);
        jScrollPane1.setViewportView(sgt_txt);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 70, 230, 170);

        label_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/360_F_823155337_DzGKTtbWRgXd5xGV42yLZqRyrX7fLsk0.jpg"))); // NOI18N
        getContentPane().add(label_img);
        label_img.setBounds(0, 0, 440, 270);

        optionsmenu.setText("opções");

        idiomamenu.setText("Idioma");

        pt_btn.setText("Português (pt-br)");
        idiomamenu.add(pt_btn);

        en_btn.setText("Inglês (en)");
        idiomamenu.add(en_btn);

        es_btn.setText("espanhol (es)");
        idiomamenu.add(es_btn);

        optionsmenu.add(idiomamenu);

        jMenuItem1.setText("Tela Inicial");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        optionsmenu.add(jMenuItem1);

        jMenuBar1.add(optionsmenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ev_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ev_btnActionPerformed
    String descricao = sgt_txt.getText();
    
    // Pegar o email do usuário logado
    String emailUsuario = UsuarioLogado.getUsuario().getEmail();

    // Chamar o método para enviar a sugestão
    bancoDeDados.adicionarSugestao(descricao, emailUsuario);
    JOptionPane.showMessageDialog(this, tradutor.traduzir("sucessoOperacao"));
    }//GEN-LAST:event_ev_btnActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaInicial tli = new TelaInicial();
        tli.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
     private void mudarIdioma(String novoIdioma) {
        tradutor = new Tradutor(Idioma.getIdiomaAtual());
        traduzirComponentes(); // Atualiza todos os textos na interface
        setTitle(tradutor.traduzir("area_de_sugestoes")); // Atualiza o título da janela
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnviarSugestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnviarSugestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnviarSugestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnviarSugestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnviarSugestoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ars_label;
    private javax.swing.JMenuItem en_btn;
    private javax.swing.JMenuItem es_btn;
    private javax.swing.JButton ev_btn;
    private javax.swing.JMenu idiomamenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_img;
    private javax.swing.JMenu optionsmenu;
    private javax.swing.JMenuItem pt_btn;
    private javax.swing.JLabel sgt_label;
    private javax.swing.JTextArea sgt_txt;
    // End of variables declaration//GEN-END:variables

    private void traduzirComponentes() {
        setTitle(tradutor.traduzir("area_de_sugestoes"));
        ars_label.setText(tradutor.traduzir("enviar_sugestoes"));
        sgt_label.setText(tradutor.traduzir("sugestao"));
        ev_btn.setText(tradutor.traduzir("enviar"));
        optionsmenu.setText(tradutor.traduzir("opcoesMenu"));
        idiomamenu.setText(tradutor.traduzir("IdiomaMenu"));
        // Atualize outros componentes com base no idioma
    }
}
