/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package interfaces;

/**
 *
 * @author gustavo.gviana
 */
public class Espaçospublico extends javax.swing.JFrame {

    /** Creates new form Espaçospublico */
    public Espaçospublico() {
        initComponents();
        pack(); // Ajusta o tamanho da janela para caber os componentes
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VilaMarianabtn = new javax.swing.JToggleButton();
        SantoAmarobtn = new javax.swing.JToggleButton();
        SãoCaetanobtn = new javax.swing.JToggleButton();
        Taboãobtn = new javax.swing.JToggleButton();
        EPvoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VilaMarianabtn.setContentAreaFilled(false);
        VilaMarianabtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VilaMarianabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VilaMarianabtnActionPerformed(evt);
            }
        });
        getContentPane().add(VilaMarianabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 130, 70));

        SantoAmarobtn.setContentAreaFilled(false);
        SantoAmarobtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SantoAmarobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SantoAmarobtnActionPerformed(evt);
            }
        });
        getContentPane().add(SantoAmarobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 110, 70));

        SãoCaetanobtn.setContentAreaFilled(false);
        SãoCaetanobtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SãoCaetanobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SãoCaetanobtnActionPerformed(evt);
            }
        });
        getContentPane().add(SãoCaetanobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 140, 70));

        Taboãobtn.setContentAreaFilled(false);
        Taboãobtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Taboãobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaboãobtnActionPerformed(evt);
            }
        });
        getContentPane().add(Taboãobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 70, 70));

        EPvoltar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        EPvoltar.setText("Voltar");
        EPvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EPvoltarActionPerformed(evt);
            }
        });
        getContentPane().add(EPvoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Ep.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VilaMarianabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VilaMarianabtnActionPerformed
        VilaMariana frame = new VilaMariana();
        frame.setVisible(true);        
    }//GEN-LAST:event_VilaMarianabtnActionPerformed

    private void SantoAmarobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SantoAmarobtnActionPerformed
        SantoAmaro fra = new SantoAmaro();
        fra.setVisible(true);
    }//GEN-LAST:event_SantoAmarobtnActionPerformed

    private void SãoCaetanobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SãoCaetanobtnActionPerformed
        SaoCaetano fram = new SaoCaetano();
        fram.setVisible(true);        
    }//GEN-LAST:event_SãoCaetanobtnActionPerformed

    private void TaboãobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaboãobtnActionPerformed
        Taboão fr = new Taboão();
        fr.setVisible(true);        
    }//GEN-LAST:event_TaboãobtnActionPerformed

    private void EPvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EPvoltarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_EPvoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Espaçospublico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Espaçospublico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Espaçospublico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Espaçospublico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Espaçospublico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EPvoltar;
    private javax.swing.JToggleButton SantoAmarobtn;
    private javax.swing.JToggleButton SãoCaetanobtn;
    private javax.swing.JToggleButton Taboãobtn;
    private javax.swing.JToggleButton VilaMarianabtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
