package interfaces;

import classes.BancoDeDados;
import classes.BusFinder;
import classes.LinhaOnibus;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author ryans
 */
public class PesquisaLinhas extends javax.swing.JFrame {
    private BancoDeDados bancoDeDados; // Instância do banco de dados
    private String partidaSelecionada; // Partida selecionada
    private BusFinder busFinder; // Instância da classe BusFinder

    /**
     * Creates new form PesquisaLinhas
     */
    public PesquisaLinhas(String partida) {
        this.partidaSelecionada = partida; // Recebe a partida da classe MapaOnibus
        bancoDeDados = new BancoDeDados(); // Inicializa o banco de dados
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ps_txt = new javax.swing.JTextField();
        ps_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ln_table = new javax.swing.JTable();
        textlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(860, 670));
        getContentPane().setLayout(null);

        ps_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(ps_txt);
        ps_txt.setBounds(60, 51, 330, 42);

        ps_btn.setText("Pesquisar Linhas");
        ps_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps_btnActionPerformed(evt);
            }
        });
        getContentPane().add(ps_btn);
        ps_btn.setBounds(510, 70, 220, 30);

        ln_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "linha ", "patida ", "destino"
            }
        ));
        jScrollPane1.setViewportView(ln_table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 130, 800, 500);

        textlabel.setText("Para onde voce quer ir ?");
        getContentPane().add(textlabel);
        textlabel.setBounds(60, 16, 310, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ps_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps_btnActionPerformed
       buscarLinhas(); // Passa a partida para a busca
    }//GEN-LAST:event_ps_btnActionPerformed

    // Método para buscar linhas e exibir na tabela
    private void buscarLinhas() {
        String destino = ps_txt.getText().trim(); // Obtém o destino digitado
        List<LinhaOnibus> linhas = bancoDeDados.buscarLinhasOnibus(partidaSelecionada, destino);
        DefaultTableModel model = (DefaultTableModel) ln_table.getModel();
        model.setRowCount(0); // Limpa a tabela antes de mostrar novos resultados

        for (LinhaOnibus linha : linhas) {
            model.addRow(new Object[]{linha.getLinha(), linha.getPartida(), linha.getDestino()}); // Adiciona cada linha encontrada à tabela
        }

        // Verifica se alguma linha foi encontrada
        if (linhas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhuma linha encontrada para o destino informado.", "Resultado", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
public static void main(String[] args) {
    SwingUtilities.invokeLater(() -> new PesquisaLinhas("Exemplo de Partida").setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ln_table;
    private javax.swing.JButton ps_btn;
    private javax.swing.JTextField ps_txt;
    private javax.swing.JLabel textlabel;
    // End of variables declaration//GEN-END:variables
}
