package interfaces;

import classes.BancoDeDados;
import classes.Idioma;
import classes.Tradutor;
import classes.Usuario;
import classes.UsuarioLogado;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ryans
 */
public class Gerenciaradmins extends javax.swing.JFrame {
    private Tradutor tradutor;
    private BancoDeDados bancoDeDados;
    /**
     * Creates new form EnviarSugestoes
     */
    public Gerenciaradmins() {
         // Obtem o usuário logado
         Usuario usuarioLogado = UsuarioLogado.getUsuario();
        // Inicializa o tradutor e o banco de dados
        tradutor = new Tradutor(Idioma.getIdiomaAtual());
        bancoDeDados = new BancoDeDados();
        initComponents();
        atualizarLabels();
        /* pega o email do usuario e carrega as sugestões obs:os codigos que envolvem
        enviar alguma coisa ao banco de voce precisara fazer login para que funcione
        porque eles utilizam o usuario logado caso voce só rode um dos jframes e não
        faça o login ira dar erro*/
        carregarUsuarios();
        
        pt_btn.addActionListener(e -> {
            Idioma.setIdiomaAtual("pt");
                    atualizarLabels();
        });

        en_btn.addActionListener(e -> {
            Idioma.setIdiomaAtual("en");
                    atualizarLabels();
        });
         es_btn.addActionListener(e -> {
            Idioma.setIdiomaAtual("es");
                    atualizarLabels();
        });
        pack(); // Ajusta o tamanho da janela para caber os componentes
        setVisible(true);
    }
     private void atualizarLabels() {
        nomelabel1.setText(tradutor.traduzir("nomeLabel") + ":");
        emaillabel1.setText(tradutor.traduzir("emailLabel") + ":");
        endlabel1.setText(tradutor.traduzir("enderecoLabel") + ":");
        mp_btn1.setText(tradutor.traduzir("modificar_permissao"));
        edt_btn1.setText(tradutor.traduzir("editar_usuario"));
        exc_btn.setText(tradutor.traduzir("excluir_usuario"));
        optionsmenu.setText(tradutor.traduzir("opcoesMenu"));
        idiomamenu.setText(tradutor.traduzir("idiomaMenu"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        sgt_tb = new javax.swing.JTable();
        em_txt2 = new javax.swing.JTextField();
        endlabel1 = new javax.swing.JLabel();
        nomelabel1 = new javax.swing.JLabel();
        end_txt1 = new javax.swing.JTextField();
        emaillabel1 = new javax.swing.JLabel();
        nm_txt1 = new javax.swing.JTextField();
        edt_btn1 = new javax.swing.JButton();
        mp_btn1 = new javax.swing.JButton();
        exc_btn = new javax.swing.JButton();
        label_img = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        optionsmenu = new javax.swing.JMenu();
        idiomamenu = new javax.swing.JMenu();
        pt_btn = new javax.swing.JMenuItem();
        en_btn = new javax.swing.JMenuItem();
        es_btn = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(937, 683));
        setResizable(false);
        getContentPane().setLayout(null);

        sgt_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Email", "Endereço", "Senha "
            }
        ));
        jScrollPane2.setViewportView(sgt_tb);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 130, 740, 510);

        em_txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                em_txt2ActionPerformed(evt);
            }
        });
        getContentPane().add(em_txt2);
        em_txt2.setBounds(210, 90, 110, 30);

        endlabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        endlabel1.setForeground(new java.awt.Color(255, 255, 255));
        endlabel1.setText("Endereço:");
        getContentPane().add(endlabel1);
        endlabel1.setBounds(390, 70, 130, 16);

        nomelabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomelabel1.setForeground(new java.awt.Color(255, 255, 255));
        nomelabel1.setText("Nome:");
        getContentPane().add(nomelabel1);
        nomelabel1.setBounds(40, 66, 110, 20);

        end_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                end_txt1ActionPerformed(evt);
            }
        });
        getContentPane().add(end_txt1);
        end_txt1.setBounds(390, 90, 110, 30);

        emaillabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emaillabel1.setForeground(new java.awt.Color(255, 255, 255));
        emaillabel1.setText("Email:");
        getContentPane().add(emaillabel1);
        emaillabel1.setBounds(210, 70, 110, 20);
        getContentPane().add(nm_txt1);
        nm_txt1.setBounds(40, 90, 110, 30);

        edt_btn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edt_btn1.setText("Editar Usuario");
        edt_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(edt_btn1);
        edt_btn1.setBounds(760, 270, 150, 40);

        mp_btn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mp_btn1.setText("modifcar permisão");
        mp_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mp_btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(mp_btn1);
        mp_btn1.setBounds(760, 200, 150, 40);

        exc_btn.setText("Excluir Usuario");
        exc_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exc_btnActionPerformed(evt);
            }
        });
        getContentPane().add(exc_btn);
        exc_btn.setBounds(760, 330, 150, 40);

        label_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/tela_fundo.jpg"))); // NOI18N
        getContentPane().add(label_img);
        label_img.setBounds(0, 0, 940, 660);

        optionsmenu.setText("opções");

        idiomamenu.setText("Idioma");

        pt_btn.setText("Português (pt-br)");
        idiomamenu.add(pt_btn);

        en_btn.setText("Inglês (en)");
        idiomamenu.add(en_btn);

        es_btn.setText("espanhol (es)");
        idiomamenu.add(es_btn);

        optionsmenu.add(idiomamenu);

        jMenuItem1.setText("Tela Inicial");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        optionsmenu.add(jMenuItem1);

        jMenuBar1.add(optionsmenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaInicial tli = new TelaInicial();
        tli.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void em_txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_em_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_em_txt2ActionPerformed

    private void end_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_end_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_end_txt1ActionPerformed

    private void mp_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mp_btn1ActionPerformed
        Usuario usuarioLogado = UsuarioLogado.getUsuario();
            int selectedRow = sgt_tb.getSelectedRow();
            if (selectedRow != -1) {
                String email = (String) sgt_tb.getValueAt(selectedRow, 1);
             boolean sucesso = bancoDeDados.mudarTipoUsuario(email);
             carregarUsuarios();
            } else {
                JOptionPane.showMessageDialog(null, "Selecione uma linha para mudar o tipo.");
            }
    }//GEN-LAST:event_mp_btn1ActionPerformed

    private void exc_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exc_btnActionPerformed
        int linhaSelecionada = sgt_tb.getSelectedRow();
        if (linhaSelecionada != -1) { // Verifica se alguma linha está selecionada
            String email = (String) sgt_tb.getValueAt(linhaSelecionada, 1); // Obtém a descrição da sugestão

            boolean sucesso = bancoDeDados.removerUsuario(email);

            if (sucesso) {
                // Remove a linha da tabela
                DefaultTableModel model = (DefaultTableModel) sgt_tb.getModel();
                model.removeRow(linhaSelecionada);
                JOptionPane.showMessageDialog(this, tradutor.traduzir("sucessoExcluirUsuario"));
                carregarUsuarios();
            } else {
                JOptionPane.showMessageDialog(this, tradutor.traduzir("erroExcluir"));
            }
        } else {
            JOptionPane.showMessageDialog(this, tradutor.traduzir("usuarioSelecionado"));
        }
    }//GEN-LAST:event_exc_btnActionPerformed

    private void edt_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_btn1ActionPerformed
String novoEmail = em_txt2.getText().trim(); // Novo e-mail
String novoNome = nm_txt1.getText().trim(); // Novo nome
String novoEndereco = end_txt1.getText().trim(); // Novo endereço
int selectedRow = sgt_tb.getSelectedRow();

if (selectedRow != -1) {
    String emailUsuario = (String) sgt_tb.getValueAt(selectedRow, 1);
    
    // Verifica se pelo menos um campo foi preenchido
    if (novoEmail.isEmpty() && novoNome.isEmpty() && novoEndereco.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha pelo menos um campo para edição.");
    } else {
        String resultado = bancoDeDados.editarUsuario(emailUsuario, 
                                                       novoEmail.isEmpty() ? null : novoEmail, 
                                                       novoNome.isEmpty() ? null : novoNome, 
                                                       novoEndereco.isEmpty() ? null : novoEndereco);
        JOptionPane.showMessageDialog(this, tradutor.traduzir(resultado)); // Usando o tradutor
        carregarUsuarios();
    }
} else {
    JOptionPane.showMessageDialog(this, "Selecione uma linha para mudar os dados do usuário.");
}

    }//GEN-LAST:event_edt_btn1ActionPerformed
// Método para carregar as sugestões na tabela
    private void carregarUsuarios() {
   DefaultTableModel tableModel = (DefaultTableModel) sgt_tb.getModel();
    tableModel.setRowCount(0); // Clear the table
    List<Usuario> usuarios = bancoDeDados.listaradmins(); // Call your database method here
     for (Usuario usuario : usuarios) {
        Object[] row = new Object[] {
            usuario.getNome(),
            usuario.getEmail(),
            usuario.getEndereco(),
            usuario.getSenha()
        };
       tableModel.addRow(row);
     }
    } 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gerenciaradmins().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton edt_btn1;
    private javax.swing.JTextField em_txt2;
    private javax.swing.JLabel emaillabel1;
    private javax.swing.JMenuItem en_btn;
    private javax.swing.JTextField end_txt1;
    private javax.swing.JLabel endlabel1;
    private javax.swing.JMenuItem es_btn;
    private javax.swing.JButton exc_btn;
    private javax.swing.JMenu idiomamenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_img;
    private javax.swing.JButton mp_btn1;
    private javax.swing.JTextField nm_txt1;
    private javax.swing.JLabel nomelabel1;
    private javax.swing.JMenu optionsmenu;
    private javax.swing.JMenuItem pt_btn;
    private javax.swing.JTable sgt_tb;
    // End of variables declaration//GEN-END:variables
}
