package interfaces;

import classes.BusFinder;


/**
 *
 * @author ryans
 */
public class MapaOnibus extends javax.swing.JFrame {
    private final BusFinder busFinder; // Instância da classe BusFinder
    /**
     * Creates new form MapaOnibus2
     */
    public MapaOnibus() {
        initComponents();
        busFinder = new BusFinder(); // Inicializa a classe BusFinder        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbds_btn = new javax.swing.JButton();
        stam_btn = new javax.swing.JButton();
        vlma_btn = new javax.swing.JButton();
        scds_btn = new javax.swing.JButton();
        mp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(939, 401));
        getContentPane().setLayout(null);

        tbds_btn.setBorderPainted(false);
        tbds_btn.setContentAreaFilled(false);
        tbds_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbds_btnActionPerformed(evt);
            }
        });
        getContentPane().add(tbds_btn);
        tbds_btn.setBounds(100, 230, 72, 70);

        stam_btn.setBorderPainted(false);
        stam_btn.setContentAreaFilled(false);
        stam_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stam_btnActionPerformed(evt);
            }
        });
        getContentPane().add(stam_btn);
        stam_btn.setBounds(270, 310, 130, 80);

        vlma_btn.setContentAreaFilled(false);
        vlma_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vlma_btnActionPerformed(evt);
            }
        });
        getContentPane().add(vlma_btn);
        vlma_btn.setBounds(460, 120, 130, 90);

        scds_btn.setBorderPainted(false);
        scds_btn.setContentAreaFilled(false);
        scds_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scds_btnActionPerformed(evt);
            }
        });
        getContentPane().add(scds_btn);
        scds_btn.setBounds(645, 200, 130, 80);

        mp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mapa.png"))); // NOI18N
        getContentPane().add(mp);
        mp.setBounds(0, 0, 940, 401);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbds_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbds_btnActionPerformed
        mostrarPesquisa("Taboão da Serra");
      //  JOptionPane.showMessageDialog(this, "teste", "Erro", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_tbds_btnActionPerformed

    private void stam_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stam_btnActionPerformed
        mostrarPesquisa("Santo Amaro");
      //  JOptionPane.showMessageDialog(this, "teste", "Erro", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_stam_btnActionPerformed

    private void vlma_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vlma_btnActionPerformed
        mostrarPesquisa("Vila Mariana");
       // JOptionPane.showMessageDialog(this, "teste", "Erro", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_vlma_btnActionPerformed

    private void scds_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scds_btnActionPerformed
        mostrarPesquisa("São Caetano");
        //JOptionPane.showMessageDialog(this, "teste", "Erro", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_scds_btnActionPerformed
    // Método para mostrar o JFrame de pesquisa
    private void mostrarPesquisa(String partida) {
        busFinder.setPartidaSelecionada(partida); // Define a partida selecionada
        PesquisaLinhas pesquisaLinhas = new PesquisaLinhas(partida); // Cria uma nova instância do JFrame de pesquisa
        pesquisaLinhas.setVisible(true); // Torna o JFrame de pesquisa visível
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapaOnibus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapaOnibus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapaOnibus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapaOnibus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapaOnibus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel mp;
    private javax.swing.JButton scds_btn;
    private javax.swing.JButton stam_btn;
    private javax.swing.JButton tbds_btn;
    private javax.swing.JButton vlma_btn;
    // End of variables declaration//GEN-END:variables
}
