package interfaces;

import classes.BancoDeDados;
import classes.Idioma;
import classes.Tradutor;
import classes.Usuario;
import classes.UsuarioLogado;
import javax.swing.JOptionPane;

/**
 *
 * @author ryans
 */
public class TelaLogin extends javax.swing.JFrame {
    private Tradutor tradutor;
    private BancoDeDados bancoDeDados;

    public TelaLogin() {
        // Solicita ao usuário que escolha um idioma
    String[] opcoes = { "Português", "Inglês", "Espanhol" };
    int escolha = JOptionPane.showOptionDialog(null, "Escolha o idioma", "Idioma",
            JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opcoes, opcoes[0]);

        if (escolha == 0) {
            Idioma.setIdiomaAtual("pt");
        } else if (escolha == 1) {
            Idioma.setIdiomaAtual("en");
        } else if (escolha == 2) {
            Idioma.setIdiomaAtual("es");
        }


        // Inicializa o tradutor e o banco de dados
        tradutor = new Tradutor(Idioma.getIdiomaAtual());
        bancoDeDados = new BancoDeDados();
        initComponents();
        atualizarLabels();
        
        pt_btn.addActionListener(e -> {
            Idioma.setIdiomaAtual("pt");
                    atualizarLabels();
        });

        en_btn.addActionListener(e -> {
            Idioma.setIdiomaAtual("en");
                    atualizarLabels();
        });
         es_btn.addActionListener(e -> {
            Idioma.setIdiomaAtual("es");
                    atualizarLabels();
        });
    }

    private void atualizarLabels() {
        setTitle(tradutor.traduzir("bemVindo"));
        emailLabel.setText(tradutor.traduzir("emailLabel"));
        senhaLabel.setText(tradutor.traduzir("senhaLabel"));
        lg_btn.setText(tradutor.traduzir("botaoLogin"));
        optionsmenu.setText(tradutor.traduzir("opcoesMenu"));
        idiomamenu.setText(tradutor.traduzir("idiomaMenu"));
        // Atualize outros componentes com base no idioma
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        em_lg = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        psw_lg = new javax.swing.JPasswordField();
        senhaLabel = new javax.swing.JLabel();
        lg_btn = new javax.swing.JButton();
        cdg_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        optionsmenu = new javax.swing.JMenu();
        idiomamenu = new javax.swing.JMenu();
        pt_btn = new javax.swing.JMenuItem();
        en_btn = new javax.swing.JMenuItem();
        es_btn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(em_lg);
        em_lg.setBounds(40, 240, 230, 50);

        emailLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emailLabel.setText("Email:");
        getContentPane().add(emailLabel);
        emailLabel.setBounds(40, 210, 230, 30);

        psw_lg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(psw_lg);
        psw_lg.setBounds(40, 340, 230, 60);

        senhaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        senhaLabel.setText("Senha:");
        getContentPane().add(senhaLabel);
        senhaLabel.setBounds(40, 306, 220, 30);

        lg_btn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lg_btn.setText("Entrar");
        lg_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lg_btnActionPerformed(evt);
            }
        });
        getContentPane().add(lg_btn);
        lg_btn.setBounds(60, 420, 180, 50);

        cdg_btn.setBackground(new java.awt.Color(242, 242, 242));
        cdg_btn.setText("Fazer Cadastro");
        cdg_btn.setBorderPainted(false);
        cdg_btn.setContentAreaFilled(false);
        cdg_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdg_btnActionPerformed(evt);
            }
        });
        getContentPane().add(cdg_btn);
        cdg_btn.setBounds(80, 480, 140, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Login.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 930, 527);

        optionsmenu.setText("opções");

        idiomamenu.setText("Idioma");

        pt_btn.setText("Português (pt-br)");
        idiomamenu.add(pt_btn);

        en_btn.setText("Inglês (en)");
        idiomamenu.add(en_btn);

        es_btn.setText("espanhol (es)");
        idiomamenu.add(es_btn);

        optionsmenu.add(idiomamenu);

        jMenuBar1.add(optionsmenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lg_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lg_btnActionPerformed
       String email = em_lg.getText();
       String senha = new String(psw_lg.getPassword());
       String resultado = bancoDeDados.validarLogin(email, senha);
       System.out.println("Resultado do login: " + resultado);
        JOptionPane.showMessageDialog(this, tradutor.traduzir("Operação realizada com sucesso"));
        Usuario usuario = bancoDeDados.obterUsuarioPorEmail(email);
        UsuarioLogado.setUsuario(usuario);
        TelaInicial tli = new TelaInicial();
        tli.setVisible(true);
        dispose();

    }//GEN-LAST:event_lg_btnActionPerformed

    private void cdg_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdg_btnActionPerformed
      CadastroUsuario cdm = new CadastroUsuario(Idioma.getIdiomaAtual());
      cdm.setVisible(true);
      dispose();
    }//GEN-LAST:event_cdg_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cdg_btn;
    private javax.swing.JTextField em_lg;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JMenuItem en_btn;
    private javax.swing.JMenuItem es_btn;
    private javax.swing.JMenu idiomamenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton lg_btn;
    private javax.swing.JMenu optionsmenu;
    private javax.swing.JPasswordField psw_lg;
    private javax.swing.JMenuItem pt_btn;
    private javax.swing.JLabel senhaLabel;
    // End of variables declaration//GEN-END:variables
}
